import "./globals.css";
import Providers from "./providers";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { ModalProvider } from "@/context/ModalContext";
import ModalManager from "@/components/modals/modalManager";
import { AlertModalBridge } from "@/components/AlertModalBridge";

export const metadata = {
  title: "OpenBK",
  description: "Generated by create next app",
  // icons: { icon: "/svg/BkIcon.svg" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ModalProvider>
            <ModalManager />
            <AlertModalBridge />
            <Navbar />
            {children}
            <Footer />
          </ModalProvider>
        </Providers>
      </body>
    </html>
  );
}